version: "3.3"
services:
  db:
    image: ghcr.io/getzep/postgres:latest
    restart: always
    shm_size: "128mb" # Increase this if vacuuming fails with a "no space left on device" error
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${ADMIN_PASSWORD}
    volumes:
      - ./zep-db:/var/lib/postgresql/data

  nlp:
    image: ghcr.io/getzep/zep-nlp-server:latest
    env_file:
      - ./.env
    restart: always

  zep:
    image: ghcr.io/getzep/zep:latest
    restart: always
    depends_on:
      - db
      - nlp
    # ports:
    #   - "172.17.0.1:30052:8000"
    volumes:
      - ./config.yaml:/app/config.yaml
    environment:
      - ZEP_STORE_POSTGRES_DSN=postgres://postgres:${ADMIN_PASSWORD}@db:5432/postgres?sslmode=disable
      - ZEP_NLP_SERVER_URL=http://nlp:5557
      - ZEP_EXTRACTORS_DOCUMENTS_EMBEDDINGS_SERVICE=openai
      - ZEP_EXTRACTORS_DOCUMENTS_EMBEDDINGS_DIMENSIONS=1536
      - ZEP_EXTRACTORS_MESSAGES_EMBEDDINGS_SERVICE=openai
      - ZEP_EXTRACTORS_MESSAGES_EMBEDDINGS_DIMENSIONS=1536
      - ZEP_EXTRACTORS_MESSAGES_SUMMARIZER_EMBEDDINGS_SERVICE=openai
      - ZEP_EXTRACTORS_MESSAGES_SUMMARIZER_EMBEDDINGS_DIMENSIONS=1536
    env_file:
      - ./.env # Store your OpenAI API key here as ZEP_OPENAI_API_KEY

  nginx:
    image: nginx
    ports:
      - 172.17.0.1:30052:80
    volumes:
      - ./nginx/:/etc/nginx/conf.d/:ro
      - ./.htpasswd:/etc/nginx/.htpasswd:ro
    restart: always
    depends_on:
      - zep
